config/routes.rb
Rails.application.routes.draw do
  root "hello#index"

  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #開発環境だけ。あとで実装csrf token
  skip_before_action :verify_authenticity_token

  def new
    @photo = Photo.new
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to @photo, notice: "Photo created successfully"
    else
      render 'new'
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/hello/index.html.erb
<div class="App">
  <header class="App-header">
    <img src="Octocat.png" class="App-logo" alt="logo" />
    <p>
      GitHub Codespaces <span class="heart">♥️</span> Rails
    </p>
    <p class="small">
      Edit <code>app/views/hello/index.html.erb</code> and see changes live!
    </p>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodespacesTryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/new.html.erb
<h1>写真をアップロード</h1>

<%= form_with model: @photo, local: true do |f| %>
  <% if @photo.errors.any? %>
    <div>
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
        <% @photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.submit "アップロード"%>
  </div>
<% end %>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>

<% if @photo.image.attached? %>
  <%= image_tag @photo.image, class: 'photo-image' %>
<% else %>
  <p>写真がアップロードされていません。</p>
<% end %>

<p><%= @photo.description %></p>

<%= link_to '一覧に戻る', photos_path %>